checking for dependencies on top and installing them globally, updating readme

diff --git a/js/pre-push b/js/pre-push
--- a/js/pre-push
+++ b/js/pre-push
@@ -1,5 +1,18 @@
 #!/bin/sh
 
+
+if ! command -v eslint &> /dev/null; then
+    echo "eslint not found! Installing..."
+    npm install -g eslint
+fi
+
+# Check if complexity-report is installed
+if ! command -v cr &> /dev/null; then
+    echo "complexity-report not found! Installing..."
+    npm install -g complexity-report
+fi
+
+
 echo "Running pre-push check..."
 
 # Get the list of changed files
@@ -8,15 +21,16 @@ files=$(git diff master --name-only --diff-filter=d)
 echo "linting..."
 for file in $files; do
     if [[ "$file" =~ \.js$ ]]; then
-        eslint_result=$(npx eslint "$file")
+        eslint_result=$(eslint "$file")
         eslint_exit_code=$?
         if [ $eslint_exit_code -ne 0 ]; then
             echo "ESLint failed for $file:"
             echo "$eslint_result"
             exit 1
         fi
-        
-        complexity_result=$(cr "$file")
+
+        # Using cr to get the complexity report
+        complexity_result=$(cr -o text "$file")
         complexity_exit_code=$?
         if [ $complexity_exit_code -ne 0 ]; then
             echo "Complexity report failed for $file:"
diff --git a/python/pre-push b/python/pre-push
--- a/python/pre-push
+++ b/python/pre-push
@@ -1,5 +1,18 @@
 #!/bin/sh
 
+
+# Check if flake8 is installed
+if ! pip list | grep -q flake8; then
+    echo "flake8 not found! Installing..."
+    pip install flake8
+fi
+
+# Check if radon is installed
+if ! pip list | grep -q radon; then
+    echo "radon not found! Installing..."
+    pip install radon
+fi
+
 echo "Running pre-push check..."
 
 # Get the list of changed files
diff --git a/ruby/pre-push b/ruby/pre-push
--- a/ruby/pre-push
+++ b/ruby/pre-push
@@ -1,5 +1,22 @@
 #!/bin/sh
 
+if ! gem list rubocop -i > /dev/null; then
+    echo "rubocop not found! Installing..."
+    gem install rubocop
+fi
+
+# Check if reek is installed
+if ! gem list reek -i > /dev/null; then
+    echo "reek not found! Installing..."
+    gem install reek
+fi
+
+# Check if flog is installed
+if ! gem list flog -i > /dev/null; then
+    echo "flog not found! Installing..."
+    gem install flog
+fi
+
 echo "Running pre-push check..."
 
 # Get the list of changed files
