Ruby and readme changes (#6)
* putting temp files in a folder instead of spreading them in the root

* removing bundle exec syntax

* adjusting flog test in ruby script + changes in the readme

* changing final message echoed

* removing file that shouldnt be on github

* updating dependecies on js

diff --git a/js/pre-push b/js/pre-push
--- a/js/pre-push
+++ b/js/pre-push
@@ -11,18 +11,6 @@ if ! command -v eslint &> /dev/null; then
     npm init @eslint/config
 fi
 
-
-if ! npm list -g eslint-plugin-css-modules &> /dev/null; then
-    echo "eslint-plugin-css-modules not found! Installing..."
-    npm install -g eslint-plugin-css-modules
-fi
-
-if ! npm list -g eslint-plugin-scss &> /dev/null; then
-    echo "eslint-plugin-scss not found! Installing..."
-    npm install -g eslint-plugin-scss
-fi
-
-
 if ! command -v tslint &> /dev/null; then
     echo "tslint not found! Installing..."
     npm install -g tslint
@@ -45,6 +33,17 @@ if ! command -v cr &> /dev/null; then
 fi
 
 
+if ! command -v stylelint &> /dev/null; then
+    echo "stylelint not found! Installing..."
+    npm install -g stylelint stylelint-config-recommended  postcss-scss
+    cho "Setting up default configuration..."
+    echo '{
+        "extends": ["stylelint-config-recommended", "stylelint-config-scss"],
+        "rules": {
+            // Add or modify rules here
+        }
+    }' > .stylelintrc.json
+fi
 
 echo "Running pre-push check..."
 
@@ -53,7 +52,7 @@ files=$(git diff master --name-only --diff-filter=d)
 
 echo "linting... $files"
 for file in $files; do
-    if [[ "$file" =~ \.js$ ]] [[ "$file" =~ \.scss$ ]] || [[ "$file" =~ \.css$ ]]; then
+    if [[ "$file" =~ \.js$ ]]; then
         echo "Running ESLint for $file"
         eslint --fix "$file"
 
@@ -75,6 +74,17 @@ for file in $files; do
             echo "$tslint_result"
             exit 1
         fi
+    elif [[ "$file" =~ \.scss$ ]] || [[ "$file" =~ \.css$ ]]; then
+        echo "Running stylelint for $file"
+        stylelint "$file" --fix
+
+        stylelint_result=$(stylelint "$file")
+        stylelint_exit_code=$?
+        if [ $stylelint_exit_code -ne 0 ]; then
+            echo "stylelint failed for $file:"
+            echo "$stylelint_result"
+            exit 1
+        fi
     fi
 
     
@@ -90,7 +100,6 @@ for file in $files; do
         fi
     fi
 done
-
 
 echo "saving diff to files..."
 DIFF_CONTENT=$(git diff master)
@@ -114,7 +123,6 @@ while [ -n "$DIFF_CONTENT" ]; do
     count=$((count + 1))
 done
 
-echo "Diffs have been saved to multiple files (pre_push_diffs/pre_push_diff_X.txt) with the prompt. Please review each file before pushing."
-
+echo "Diffs have been saved to multiple files (pre_push_diffs/pre_push_diff_X.txt) with the prompt. You can promp AI chatbots to review your code diffs."
 
 exit 0
